language: java
os:
  - linux
  - osx
before_install:
  - chmod +x gradlew
test:
  post:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)